apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamlgenerator
  labels:
    app: yaml-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaml-generator
  template:
    metadata:
      labels:
        app: yaml-generator
    spec:
      containers:
      - name: yaml-generator
        image: gokalpmeric/yamlgenerator:0.0.1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"

